# Dockerfile.storybook (build stage)
FROM node:20-alpine AS build
WORKDIR /app/client

COPY client/package.json client/package-lock.json ./
RUN npm ci
COPY client/ ./


# Build static Storybook (outputs storybook-static/)
RUN npm run build-storybook
