/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(app)': RouteRecordInfo<
      '/(app)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '/(app)/'
      | '/(app)/analyze/'
      | '/(app)/applications-search/'
      | '/(app)/assessment-tool/'
      | '/(app)/assessment-tool/[id]/'
      | '/(app)/assessment-tool/create/'
      | '/(app)/certificate/'
      | '/(app)/connection-configuration/'
      | '/(app)/connection-configuration/[id]/'
      | '/(app)/connection-configuration/create/'
      | '/(app)/exam-template/'
      | '/(app)/exam-template/[id]/'
      | '/(app)/exam-template/create/'
      | '/(app)/exam/'
      | '/(app)/exam/[id]/'
      | '/(app)/exam/create/'
      | '/(app)/gallery_[uuid]_[examId]/'
      | '/(app)/institution/'
      | '/(app)/institution/[id]/'
      | '/(app)/institution/create/'
      | '/(app)/monitoring/'
      | '/(app)/monitoring/[examId]/'
      | '/(app)/monitoring/[examId]/client/'
      | '/(app)/monitoring/[examId]/client/[connectionToken]/'
      | '/(app)/navigation-overview/'
      | '/(app)/notification-playground/'
      | '/(app)/sp-recording/[sessionId]/'
      | '/(app)/sp-recording/application-search/[sessionId]/'
      | '/(app)/sp-search/'
      | '/(app)/user-account/'
      | '/(app)/user-account/[userUuid]/'
      | '/(app)/user-account/create/'
      | '/(app)/user-account/profile/'
    >,
    '/(app)/': RouteRecordInfo<
      '/(app)/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(app)/analyze/': RouteRecordInfo<
      '/(app)/analyze/',
      '/analyze',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(app)/applications-search/': RouteRecordInfo<
      '/(app)/applications-search/',
      '/applications-search',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(app)/assessment-tool/': RouteRecordInfo<
      '/(app)/assessment-tool/',
      '/assessment-tool',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(app)/assessment-tool/[id]/': RouteRecordInfo<
      '/(app)/assessment-tool/[id]/',
      '/assessment-tool/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(app)/assessment-tool/create/': RouteRecordInfo<
      '/(app)/assessment-tool/create/',
      '/assessment-tool/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(app)/certificate/': RouteRecordInfo<
      '/(app)/certificate/',
      '/certificate',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(app)/connection-configuration/': RouteRecordInfo<
      '/(app)/connection-configuration/',
      '/connection-configuration',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(app)/connection-configuration/[id]/': RouteRecordInfo<
      '/(app)/connection-configuration/[id]/',
      '/connection-configuration/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(app)/connection-configuration/create/': RouteRecordInfo<
      '/(app)/connection-configuration/create/',
      '/connection-configuration/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(app)/exam/': RouteRecordInfo<
      '/(app)/exam/',
      '/exam',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(app)/exam/[id]/': RouteRecordInfo<
      '/(app)/exam/[id]/',
      '/exam/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(app)/exam/create/': RouteRecordInfo<
      '/(app)/exam/create/',
      '/exam/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(app)/exam-template/': RouteRecordInfo<
      '/(app)/exam-template/',
      '/exam-template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(app)/exam-template/[id]/': RouteRecordInfo<
      '/(app)/exam-template/[id]/',
      '/exam-template/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(app)/exam-template/create/': RouteRecordInfo<
      '/(app)/exam-template/create/',
      '/exam-template/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(app)/gallery_[uuid]_[examId]/': RouteRecordInfo<
      '/(app)/gallery_[uuid]_[examId]/',
      '/gallery_:uuid()_:examId',
      { uuid: ParamValue<true>, examId: ParamValue<true> },
      { uuid: ParamValue<false>, examId: ParamValue<false> },
      | never
    >,
    '/(app)/institution/': RouteRecordInfo<
      '/(app)/institution/',
      '/institution',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(app)/institution/[id]/': RouteRecordInfo<
      '/(app)/institution/[id]/',
      '/institution/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(app)/institution/create/': RouteRecordInfo<
      '/(app)/institution/create/',
      '/institution/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(app)/monitoring/': RouteRecordInfo<
      '/(app)/monitoring/',
      '/monitoring',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(app)/monitoring/[examId]/': RouteRecordInfo<
      '/(app)/monitoring/[examId]/',
      '/monitoring/:examId',
      { examId: ParamValue<true> },
      { examId: ParamValue<false> },
      | never
    >,
    '/(app)/monitoring/[examId]/client/': RouteRecordInfo<
      '/(app)/monitoring/[examId]/client/',
      '/monitoring/:examId/client',
      { examId: ParamValue<true> },
      { examId: ParamValue<false> },
      | never
    >,
    '/(app)/monitoring/[examId]/client/[connectionToken]/': RouteRecordInfo<
      '/(app)/monitoring/[examId]/client/[connectionToken]/',
      '/monitoring/:examId/client/:connectionToken',
      { examId: ParamValue<true>, connectionToken: ParamValue<true> },
      { examId: ParamValue<false>, connectionToken: ParamValue<false> },
      | never
    >,
    '/(app)/navigation-overview/': RouteRecordInfo<
      '/(app)/navigation-overview/',
      '/navigation-overview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(app)/sp-recording/[sessionId]/': RouteRecordInfo<
      '/(app)/sp-recording/[sessionId]/',
      '/sp-recording/:sessionId',
      { sessionId: ParamValue<true> },
      { sessionId: ParamValue<false> },
      | never
    >,
    '/(app)/sp-recording/application-search/[sessionId]/': RouteRecordInfo<
      '/(app)/sp-recording/application-search/[sessionId]/',
      '/sp-recording/application-search/:sessionId',
      { sessionId: ParamValue<true> },
      { sessionId: ParamValue<false> },
      | never
    >,
    '/(app)/sp-search/': RouteRecordInfo<
      '/(app)/sp-search/',
      '/sp-search',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(app)/user-account/': RouteRecordInfo<
      '/(app)/user-account/',
      '/user-account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(app)/user-account/[userUuid]/': RouteRecordInfo<
      '/(app)/user-account/[userUuid]/',
      '/user-account/:userUuid',
      { userUuid: ParamValue<true> },
      { userUuid: ParamValue<false> },
      | never
    >,
    '/(app)/user-account/create/': RouteRecordInfo<
      '/(app)/user-account/create/',
      '/user-account/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(app)/user-account/profile/': RouteRecordInfo<
      '/(app)/user-account/profile/',
      '/user-account/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(public)': RouteRecordInfo<
      '/(public)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '/(public)/login/'
      | '/(public)/register/'
    >,
    '/(public)/login/': RouteRecordInfo<
      '/(public)/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(public)/register/': RouteRecordInfo<
      '/(public)/register/',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(app).vue': {
      routes:
        | '/(app)'
        | '/(app)/'
        | '/(app)/analyze/'
        | '/(app)/applications-search/'
        | '/(app)/assessment-tool/'
        | '/(app)/assessment-tool/[id]/'
        | '/(app)/assessment-tool/create/'
        | '/(app)/certificate/'
        | '/(app)/connection-configuration/'
        | '/(app)/connection-configuration/[id]/'
        | '/(app)/connection-configuration/create/'
        | '/(app)/exam-template/'
        | '/(app)/exam-template/[id]/'
        | '/(app)/exam-template/create/'
        | '/(app)/exam/'
        | '/(app)/exam/[id]/'
        | '/(app)/exam/create/'
        | '/(app)/gallery_[uuid]_[examId]/'
        | '/(app)/institution/'
        | '/(app)/institution/[id]/'
        | '/(app)/institution/create/'
        | '/(app)/monitoring/'
        | '/(app)/monitoring/[examId]/'
        | '/(app)/monitoring/[examId]/client/'
        | '/(app)/monitoring/[examId]/client/[connectionToken]/'
        | '/(app)/navigation-overview/'
        | '/(app)/sp-recording/[sessionId]/'
        | '/(app)/sp-recording/application-search/[sessionId]/'
        | '/(app)/sp-search/'
        | '/(app)/user-account/'
        | '/(app)/user-account/[userUuid]/'
        | '/(app)/user-account/create/'
        | '/(app)/user-account/profile/'
      views:
        | 'default'
    }
    'src/pages/(app)/index.vue': {
      routes:
        | '/(app)/'
      views:
        | never
    }
    'src/pages/(app)/analyze/index.vue': {
      routes:
        | '/(app)/analyze/'
      views:
        | never
    }
    'src/pages/(app)/applications-search/index.vue': {
      routes:
        | '/(app)/applications-search/'
      views:
        | never
    }
    'src/pages/(app)/assessment-tool/index.vue': {
      routes:
        | '/(app)/assessment-tool/'
      views:
        | never
    }
    'src/pages/(app)/assessment-tool/[id]/index.vue': {
      routes:
        | '/(app)/assessment-tool/[id]/'
      views:
        | never
    }
    'src/pages/(app)/assessment-tool/create/index.vue': {
      routes:
        | '/(app)/assessment-tool/create/'
      views:
        | never
    }
    'src/pages/(app)/certificate/index.vue': {
      routes:
        | '/(app)/certificate/'
      views:
        | never
    }
    'src/pages/(app)/connection-configuration/index.vue': {
      routes:
        | '/(app)/connection-configuration/'
      views:
        | never
    }
    'src/pages/(app)/connection-configuration/[id]/index.vue': {
      routes:
        | '/(app)/connection-configuration/[id]/'
      views:
        | never
    }
    'src/pages/(app)/connection-configuration/create/index.vue': {
      routes:
        | '/(app)/connection-configuration/create/'
      views:
        | never
    }
    'src/pages/(app)/exam/index.vue': {
      routes:
        | '/(app)/exam/'
      views:
        | never
    }
    'src/pages/(app)/exam/[id]/index.vue': {
      routes:
        | '/(app)/exam/[id]/'
      views:
        | never
    }
    'src/pages/(app)/exam/create/index.vue': {
      routes:
        | '/(app)/exam/create/'
      views:
        | never
    }
    'src/pages/(app)/exam-template/index.vue': {
      routes:
        | '/(app)/exam-template/'
      views:
        | never
    }
    'src/pages/(app)/exam-template/[id]/index.vue': {
      routes:
        | '/(app)/exam-template/[id]/'
      views:
        | never
    }
    'src/pages/(app)/exam-template/create/index.vue': {
      routes:
        | '/(app)/exam-template/create/'
      views:
        | never
    }
    'src/pages/(app)/gallery_[uuid]_[examId]/index.vue': {
      routes:
        | '/(app)/gallery_[uuid]_[examId]/'
      views:
        | never
    }
    'src/pages/(app)/institution/index.vue': {
      routes:
        | '/(app)/institution/'
      views:
        | never
    }
    'src/pages/(app)/institution/[id]/index.vue': {
      routes:
        | '/(app)/institution/[id]/'
      views:
        | never
    }
    'src/pages/(app)/institution/create/index.vue': {
      routes:
        | '/(app)/institution/create/'
      views:
        | never
    }
    'src/pages/(app)/monitoring/index.vue': {
      routes:
        | '/(app)/monitoring/'
      views:
        | never
    }
    'src/pages/(app)/monitoring/[examId]/index.vue': {
      routes:
        | '/(app)/monitoring/[examId]/'
      views:
        | never
    }
    'src/pages/(app)/monitoring/[examId]/client/index.vue': {
      routes:
        | '/(app)/monitoring/[examId]/client/'
      views:
        | never
    }
    'src/pages/(app)/monitoring/[examId]/client/[connectionToken]/index.vue': {
      routes:
        | '/(app)/monitoring/[examId]/client/[connectionToken]/'
      views:
        | never
    }
    'src/pages/(app)/navigation-overview/index.vue': {
      routes:
        | '/(app)/navigation-overview/'
      views:
        | never
    }
    'src/pages/(app)/sp-recording/[sessionId]/index.vue': {
      routes:
        | '/(app)/sp-recording/[sessionId]/'
      views:
        | never
    }
    'src/pages/(app)/sp-recording/application-search/[sessionId]/index.vue': {
      routes:
        | '/(app)/sp-recording/application-search/[sessionId]/'
      views:
        | never
    }
    'src/pages/(app)/sp-search/index.vue': {
      routes:
        | '/(app)/sp-search/'
      views:
        | never
    }
    'src/pages/(app)/user-account/index.vue': {
      routes:
        | '/(app)/user-account/'
      views:
        | never
    }
    'src/pages/(app)/user-account/[userUuid]/index.vue': {
      routes:
        | '/(app)/user-account/[userUuid]/'
      views:
        | never
    }
    'src/pages/(app)/user-account/create/index.vue': {
      routes:
        | '/(app)/user-account/create/'
      views:
        | never
    }
    'src/pages/(app)/user-account/profile/index.vue': {
      routes:
        | '/(app)/user-account/profile/'
      views:
        | never
    }
    'src/pages/(public).vue': {
      routes:
        | '/(public)'
        | '/(public)/login/'
        | '/(public)/register/'
      views:
        | 'default'
    }
    'src/pages/(public)/login/index.vue': {
      routes:
        | '/(public)/login/'
      views:
        | never
    }
    'src/pages/(public)/register/index.vue': {
      routes:
        | '/(public)/register/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
