/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(app)': RouteRecordInfo<
      '/(app)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '/(app)/assessment-tool/'
      | '/(app)/home/'
      | '/(app)/navigation-overview/'
      | '/(app)/user-account/'
      | '/(app)/user-account/[userUuid]/'
      | '/(app)/user-account/create/'
      | '/(app)/user-account/profile/'
    >,
    '/(app)/assessment-tool/': RouteRecordInfo<
      '/(app)/assessment-tool/',
      '/assessment-tool',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(app)/home/': RouteRecordInfo<
      '/(app)/home/',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(app)/navigation-overview/': RouteRecordInfo<
      '/(app)/navigation-overview/',
      '/navigation-overview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(app)/user-account/': RouteRecordInfo<
      '/(app)/user-account/',
      '/user-account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(app)/user-account/[userUuid]/': RouteRecordInfo<
      '/(app)/user-account/[userUuid]/',
      '/user-account/:userUuid',
      { userUuid: ParamValue<true> },
      { userUuid: ParamValue<false> },
      | never
    >,
    '/(app)/user-account/create/': RouteRecordInfo<
      '/(app)/user-account/create/',
      '/user-account/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(app)/user-account/profile/': RouteRecordInfo<
      '/(app)/user-account/profile/',
      '/user-account/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(public)': RouteRecordInfo<
      '/(public)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '/(public)/'
      | '/(public)/register/'
    >,
    '/(public)/': RouteRecordInfo<
      '/(public)/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(public)/register/': RouteRecordInfo<
      '/(public)/register/',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(app).vue': {
      routes:
        | '/(app)'
        | '/(app)/assessment-tool/'
        | '/(app)/home/'
        | '/(app)/navigation-overview/'
        | '/(app)/user-account/'
        | '/(app)/user-account/[userUuid]/'
        | '/(app)/user-account/create/'
        | '/(app)/user-account/profile/'
      views:
        | 'default'
    }
    'src/pages/(app)/assessment-tool/index.vue': {
      routes:
        | '/(app)/assessment-tool/'
      views:
        | never
    }
    'src/pages/(app)/home/index.vue': {
      routes:
        | '/(app)/home/'
      views:
        | never
    }
    'src/pages/(app)/navigation-overview/index.vue': {
      routes:
        | '/(app)/navigation-overview/'
      views:
        | never
    }
    'src/pages/(app)/user-account/index.vue': {
      routes:
        | '/(app)/user-account/'
      views:
        | never
    }
    'src/pages/(app)/user-account/[userUuid]/index.vue': {
      routes:
        | '/(app)/user-account/[userUuid]/'
      views:
        | never
    }
    'src/pages/(app)/user-account/create/index.vue': {
      routes:
        | '/(app)/user-account/create/'
      views:
        | never
    }
    'src/pages/(app)/user-account/profile/index.vue': {
      routes:
        | '/(app)/user-account/profile/'
      views:
        | never
    }
    'src/pages/(public).vue': {
      routes:
        | '/(public)'
        | '/(public)/'
        | '/(public)/register/'
      views:
        | 'default'
    }
    'src/pages/(public)/index.vue': {
      routes:
        | '/(public)/'
      views:
        | never
    }
    'src/pages/(public)/register/index.vue': {
      routes:
        | '/(public)/register/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
