/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddClientGroup: typeof import('./components/views/client-group/AddClientGroup.vue')['default']
    AddClientGroupDialog: typeof import('./components/views/client-group/AddClientGroupDialog.vue')['default']
    AlertMsg: typeof import('./components/widgets/AlertMsg.vue')['default']
    ContainerLayout: typeof import('./components/layout/ContainerLayout.vue')['default']
    copy: typeof import('./components/views/exam/main-content/ExamDetailSupervisorsDialog copy.vue')['default']
    ErrorMsg: typeof import('./components/widgets/ErrorMsg.vue')['default']
    ExamDetailArchiveDialog: typeof import('./components/views/exam/main-content/ExamDetailArchiveDialog.vue')['default']
    ExamDetailConfigDialog: typeof import('./components/views/exam/main-content/ExamDetailConfigDialog.vue')['default']
    ExamDetailContainer: typeof import('./components/views/exam/ExamDetailContainer.vue')['default']
    ExamDetailDeleteDialog: typeof import('./components/views/exam/main-content/ExamDetailDeleteDialog.vue')['default']
    ExamDetailGroupDialog: typeof import('./components/views/exam/main-content/ExamDetailGroupDialog.vue')['default']
    ExamDetailInfo: typeof import('./components/views/exam/info-box-content/ExamDetailInfo.vue')['default']
    ExamDetailMain: typeof import('./components/views/exam/main-content/ExamDetailMain.vue')['default']
    ExamDetailSupervisorsDialog: typeof import('./components/views/exam/main-content/ExamDetailSupervisorsDialog.vue')['default']
    ExamListContainer: typeof import('./components/views/exam/ExamListContainer.vue')['default']
    ExamListInfo: typeof import('./components/views/exam/info-box-content/ExamListInfo.vue')['default']
    ExamListMain: typeof import('./components/views/exam/main-content/ExamListMain.vue')['default']
    ExamTemplateDialog: typeof import('./components/widgets/ExamTemplateDialog.vue')['default']
    HomePage: typeof import('./components/views/home/HomePage.vue')['default']
    ImportAssessmentInfo: typeof import('./components/views/quiz-import/info-box-content/ImportAssessmentInfo.vue')['default']
    ImportAssessmentMain: typeof import('./components/views/quiz-import/main-content/ImportAssessmentMain.vue')['default']
    ImportExamInfo: typeof import('./components/views/quiz-import/info-box-content/ImportExamInfo.vue')['default']
    ImportExamMain: typeof import('./components/views/quiz-import/main-content/ImportExamMain.vue')['default']
    ImportGenericInfo: typeof import('./components/views/quiz-import/info-box-content/ImportGenericInfo.vue')['default']
    ImportGroupInfo: typeof import('./components/views/quiz-import/info-box-content/ImportGroupInfo.vue')['default']
    ImportGroupMain: typeof import('./components/views/quiz-import/main-content/ImportGroupMain.vue')['default']
    ImportPasswordInfo: typeof import('./components/views/quiz-import/info-box-content/ImportPasswordInfo.vue')['default']
    ImportPasswordMain: typeof import('./components/views/quiz-import/main-content/ImportPasswordMain.vue')['default']
    ImportSummaryInfo: typeof import('./components/views/quiz-import/info-box-content/ImportSummaryInfo.vue')['default']
    ImportSummaryMain: typeof import('./components/views/quiz-import/main-content/ImportSummaryMain.vue')['default']
    ImportSupervisorInfo: typeof import('./components/views/quiz-import/info-box-content/ImportSupervisorInfo.vue')['default']
    ImportSupervisorMain: typeof import('./components/views/quiz-import/main-content/ImportSupervisorMain.vue')['default']
    ImportTemplateInfo: typeof import('./components/views/quiz-import/info-box-content/ImportTemplateInfo.vue')['default']
    ImportTemplateMain: typeof import('./components/views/quiz-import/main-content/ImportTemplateMain.vue')['default']
    ImportWizard: typeof import('./components/views/quiz-import/ImportWizard.vue')['default']
    LoginPage: typeof import('./components/views/LoginPage.vue')['default']
    MonitoringMain: typeof import('./components/views/monitoring/MonitoringMain.vue')['default']
    NavigationOverview: typeof import('./components/layout/NavigationOverview.vue')['default']
    RegisterPage: typeof import('./components/views/RegisterPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SebSettingsApplications: typeof import('./components/views/settings/SebSettingsApplications.vue')['default']
    SebSettingsDialog: typeof import('./components/views/settings/SebSettingsDialog.vue')['default']
    TemplateDescriptionDialog: typeof import('./components/widgets/TemplateDescriptionDialog.vue')['default']
  }
}
