/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertMsg: typeof import('./components/widgets/AlertMsg.vue')['default']
    ContainerLayout: typeof import('./components/layout/ContainerLayout.vue')['default']
    ExamDatailsMain: typeof import('./components/views/exam/ExamDatailsMain.vue')['default']
    ExamDetail: typeof import('./components/views/exam/main-content/ExamDetail.vue')['default']
    ExamListMain: typeof import('./components/views/exam/ExamListMain.vue')['default']
    ExamsDatailsMain: typeof import('./components/views/exam/ExamsDatailsMain.vue')['default']
    ExamsListMain: typeof import('./components/views/exam/ExamsListMain.vue')['default']
    ExamsMain: typeof import('./components/views/exam/ExamsMain.vue')['default']
    HomePage: typeof import('./components/views/home/HomePage.vue')['default']
    InfoBoxExam: typeof import('./components/views/quiz-import/info-box-content/InfoBoxExam.vue')['default']
    InfoBoxExamDetail: typeof import('./components/views/exam/info-box-content/InfoBoxExamDetail.vue')['default']
    InfoBoxExamList: typeof import('./components/views/exam/info-box-content/InfoBoxExamList.vue')['default']
    InfoBoxGeneric: typeof import('./components/views/quiz-import/info-box-content/InfoBoxGeneric.vue')['default']
    InfoBoxPassword: typeof import('./components/views/quiz-import/info-box-content/InfoBoxPassword.vue')['default']
    InfoBoxSummary: typeof import('./components/views/quiz-import/info-box-content/InfoBoxSummary.vue')['default']
    InfoBoxSupervisor: typeof import('./components/views/quiz-import/info-box-content/InfoBoxSupervisor.vue')['default']
    InfoBoxTemplate: typeof import('./components/views/quiz-import/info-box-content/InfoBoxTemplate.vue')['default']
    LoginPage: typeof import('./components/views/LoginPage.vue')['default']
    MainContentExam: typeof import('./components/views/quiz-import/main-content/MainContentExam.vue')['default']
    MainContentExamDetail: typeof import('./components/views/exam/main-content/MainContentExamDetail.vue')['default']
    MainContentExamList: typeof import('./components/views/exam/main-content/MainContentExamList.vue')['default']
    MainContentPassword: typeof import('./components/views/quiz-import/main-content/MainContentPassword.vue')['default']
    MainContentSummary: typeof import('./components/views/quiz-import/main-content/MainContentSummary.vue')['default']
    MainContentSupervisor: typeof import('./components/views/quiz-import/main-content/MainContentSupervisor.vue')['default']
    MainContentTemplate: typeof import('./components/views/quiz-import/main-content/MainContentTemplate.vue')['default']
    MonitoringMain: typeof import('./components/views/monitoring/MonitoringMain.vue')['default']
    NavigationOverview: typeof import('./components/layout/NavigationOverview.vue')['default']
    QuizImportWizard: typeof import('./components/views/quiz-import/QuizImportWizard.vue')['default']
    RegisterPage: typeof import('./components/views/RegisterPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
