/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertMsg: typeof import('./components/widgets/AlertMsg.vue')['default']
    ContainerLayout: typeof import('./components/layout/ContainerLayout.vue')['default']
    ExamLmsImport: typeof import('./components/views/exam/ExamLmsImport.vue')['default']
    ExamsMain: typeof import('./components/views/exam/ExamsMain.vue')['default']
    HomePage: typeof import('./components/views/home/HomePage.vue')['default']
    LoginPage: typeof import('./components/views/LoginPage.vue')['default']
    MonitoringMain: typeof import('./components/views/monitoring/MonitoringMain.vue')['default']
    NavigationOverview: typeof import('./components/views/navigation/NavigationOverview.vue')['default']
    RegisterPage: typeof import('./components/views/RegisterPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StartPage: typeof import('./components/views/home/StartPage.vue')['default']
  }
}
