export enum CertificateTypeEnum {
    UNKNOWN = "UNKNOWN",
    DIGITAL_SIGNATURE = "DIGITAL_SIGNATURE",
    DATA_ENCIPHERMENT = "DATA_ENCIPHERMENT",
    DATA_ENCIPHERMENT_PRIVATE_KEY = "DATA_ENCIPHERMENT_PRIVATE_KEY",
    KEY_CERT_SIGN = "KEY_CERT_SIGN",
}
