export enum FeatureEnum {
    ADMIN_INSTITUTION,
    ADMIN_USER_ADMINISTRATION,
    ADMIN_USER_ACCOUNT,
    ADMIN_USER_ACCOUNT_SELF_REGISTERING,
    ADMIN_USER_ACCOUNT_SELF_REGISTERING_AUTO_ACTIVATION,
    ADMIN_AUDIT_LOGS,

    CONFIG_CONNECTION_CONFIGURATION,
    CONFIG_EXAM_CONFIGURATION,
    CONFIG_TEMPLATE,
    CONFIG_CERTIFICATE,
    LMS_SETUP,
    LMS_SETUP_TEST,
    LMS_SETUP_MOODLE,
    LMS_SETUP_MOODLE_PLUGIN,
    LMS_SETUP_OPEN_EDX,
    LMS_SETUP_ANS,
    LMS_SETUP_OLAT,

    QUIZ_LOOKUP,

    EXAM_ADMIN,
    EXAM_ASK,
    EXAM_CONNECTION_CONFIG,
    EXAM_SEB_RESTRICTION,
    EXAM_LIVE_PROCTORING,
    EXAM_NO_LMS,

    EXAM_SCREEN_PROCTORING,
    EXAM_INDICATORS,
    EXAM_SEB_CLIENT_GROUPS,
    EXAM_TEMPLATE,

    MONITORING_RUNNING_EXAMS,
    MONITORING_RUNNING_EXAM_DETAIL_VIEW,
    MONITORING_RUNNING_EXAM_DETAIL_VIEW_LOG_EXPORT,
    MONITORING_RUNNING_EXAM_QUIT,
    MONITORING_RUNNING_EXAM_LOCKSCREEN,
    MONITORING_RUNNING_EXAM_CANCEL_CON,
    MONITORING_RUNNING_EXAM_STATE_FILTER,
    MONITORING_RUNNING_EXAM_ISSUE_FILTER,
    MONITORING_RUNNING_EXAM_CLIENT_FILTER,
    MONITORING_RUNNING_EXAM_LIVE_PROCTORING,
    MONITORING_RUNNING_EXAM_SCREEN_PROCTORING,
    MONITORING_FINISHED_EXAMS,
    MONITORING_OVERALL_LOG_EXPORT,
}

export const featureNameMapping = new Map<FeatureEnum, string>([
    [FeatureEnum.ADMIN_INSTITUTION, "admin.institution"],
    [FeatureEnum.ADMIN_USER_ADMINISTRATION, "admin.user.administration"],
    [FeatureEnum.ADMIN_USER_ACCOUNT, "admin.user.account"],
    [
        FeatureEnum.ADMIN_USER_ACCOUNT_SELF_REGISTERING,
        "admin.user.account.self.registering",
    ],
    [
        FeatureEnum.ADMIN_USER_ACCOUNT_SELF_REGISTERING_AUTO_ACTIVATION,
        "admin.user.account.self.registering.autoactivation",
    ],
    [FeatureEnum.ADMIN_AUDIT_LOGS, "admin.auditlogs"],
    [
        FeatureEnum.CONFIG_CONNECTION_CONFIGURATION,
        "config.connection.configuration",
    ],
    [FeatureEnum.CONFIG_EXAM_CONFIGURATION, "config.exam.configuration"],
    [FeatureEnum.CONFIG_TEMPLATE, "config.template"],
    [FeatureEnum.CONFIG_CERTIFICATE, "config.certificate"],
    [FeatureEnum.LMS_SETUP, "lms.setup"],
    [FeatureEnum.LMS_SETUP_TEST, "lms.setup.type.MOCKUP"],
    [FeatureEnum.LMS_SETUP_MOODLE, "lms.setup.type.MOODLE"],
    [FeatureEnum.LMS_SETUP_MOODLE_PLUGIN, "lms.setup.type.MOODLE_PLUGIN"],
    [FeatureEnum.LMS_SETUP_OPEN_EDX, "lms.setup.type.OPEN_EDX"],
    [FeatureEnum.LMS_SETUP_ANS, "lms.setup.type.ANS_DELFT"],
    [FeatureEnum.LMS_SETUP_OLAT, "lms.setup.type.OLAT"],
    [FeatureEnum.QUIZ_LOOKUP, "lms.quiz.lookup"],
    [FeatureEnum.EXAM_ADMIN, "exam.administration"],
    [FeatureEnum.EXAM_ASK, "exam.ask"],
    [FeatureEnum.EXAM_CONNECTION_CONFIG, "exam.connection.config"],
    [FeatureEnum.EXAM_SEB_RESTRICTION, "exam.seb.restriction"],
    [FeatureEnum.EXAM_LIVE_PROCTORING, "exam.seb.liveProctoring"],
    [FeatureEnum.EXAM_NO_LMS, "exam.noLMS"],
    [FeatureEnum.EXAM_SCREEN_PROCTORING, "exam.seb.screenProctoring"],
    [FeatureEnum.EXAM_INDICATORS, "exam.monitoring.indicators"],
    [FeatureEnum.EXAM_SEB_CLIENT_GROUPS, "exam.seb.clientgroups"],
    [FeatureEnum.EXAM_TEMPLATE, "exam.template"],
    [FeatureEnum.MONITORING_RUNNING_EXAMS, "monitoring.running.exams"],
    [
        FeatureEnum.MONITORING_RUNNING_EXAM_DETAIL_VIEW,
        "monitoring.running.exam.detailview",
    ],
    [
        FeatureEnum.MONITORING_RUNNING_EXAM_DETAIL_VIEW_LOG_EXPORT,
        "monitoring.running.exam.detailview.logexport",
    ],
    [FeatureEnum.MONITORING_RUNNING_EXAM_QUIT, "monitoring.running.exam.quit"],
    [
        FeatureEnum.MONITORING_RUNNING_EXAM_LOCKSCREEN,
        "monitoring.running.exam.lockscreen",
    ],
    [
        FeatureEnum.MONITORING_RUNNING_EXAM_CANCEL_CON,
        "monitoring.running.exam.cancel.connection",
    ],
    [
        FeatureEnum.MONITORING_RUNNING_EXAM_STATE_FILTER,
        "monitoring.running.exam.state.filter",
    ],
    [
        FeatureEnum.MONITORING_RUNNING_EXAM_ISSUE_FILTER,
        "monitoring.running.exam.issue.filter",
    ],
    [
        FeatureEnum.MONITORING_RUNNING_EXAM_CLIENT_FILTER,
        "monitoring.running.exam.client.filter",
    ],
    [
        FeatureEnum.MONITORING_RUNNING_EXAM_LIVE_PROCTORING,
        "monitoring.running.exam.live.proctoring",
    ],
    [
        FeatureEnum.MONITORING_RUNNING_EXAM_SCREEN_PROCTORING,
        "monitoring.running.exam.screen.proctoring",
    ],
    [FeatureEnum.MONITORING_FINISHED_EXAMS, "monitoring.finished.exams"],
    [FeatureEnum.MONITORING_OVERALL_LOG_EXPORT, "monitoring.overall.export"],
]);
