export enum UserRoleEnum {
    SEB_SERVER_ADMIN = "SEB_SERVER_ADMIN",
    INSTITUTIONAL_ADMIN = "INSTITUTIONAL_ADMIN",
    EXAM_ADMIN = "EXAM_ADMIN",
    EXAM_SUPPORTER = "EXAM_SUPPORTER",
    TEACHER = "TEACHER"
}